credentials = {
    'ssid' : 'DIT HOTSPOT/ACCES POINT NAVN',
    'password' : 'DIT HOTSPOT/ACCES POINT PASSWORD',
    'ADAFRUIT_IO_URL' : b'io.adafruit.com',
    'ADAFRUIT_USERNAME' : b'DIT ADAFRUIT BRUGERNAVN',
    'ADAFRUIT_IO_KEY' : b'DIN ADAFRUIT IO KEY',
    'ADAFRUIT_IO_FEEDNAME' : b'ESP32feed'
    }